development:
  adapter:  postgresql
  database: simple_angular_dev
  user:     dev
  password: dev

test:
  adapter:  postgresql
  database: simple_angular_test
  user:     dev
  password: dev

production:
  adapter:  postgresql
  database: simple_angular_prod

